import type { Metadata } from "next";
import Footer from "./components/shared/Footer";
import NavigationPage from "./components/shared/Navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <div>
    <NavigationPage/>
    {children}
    <Footer/>
   </div>
  );
}
